Repository typelevel/frameless, pull requests merged in 2021-09, with the labels that each got.

#560 Set MIMA plugin for the project
  .github/workflows/ci.yml
  build.sbt
  project/plugins.sbt
Labels: build/process improvement

#449 Dotted syntax (via lambda) for TypedColumns
  dataset/src/main/scala/frameless/TypedColumn.scala
  dataset/src/main/scala/frameless/TypedColumnMacroImpl.scala
  dataset/src/main/scala/frameless/TypedDataset.scala
  dataset/src/main/scala/frameless/With.scala
  dataset/src/test/scala/frameless/ColumnTests.scala
  dataset/src/test/scala/frameless/ColumnViaLambdaTests.scala
Labels: feature

#546 Encode Value class field using the inner type
  README.md
  build.sbt
  dataset/src/main/scala/frameless/IsValueClass.scala
  dataset/src/main/scala/frameless/RecordEncoder.scala
  dataset/src/main/scala/frameless/TypedColumn.scala
  dataset/src/main/scala/frameless/TypedExpressionEncoder.scala
  dataset/src/main/scala/frameless/functions/Lit.scala
  dataset/src/main/scala/frameless/functions/package.scala
  dataset/src/test/resources/log4j.properties
  dataset/src/test/scala/frameless/BitwiseTests.scala
  dataset/src/test/scala/frameless/IsValueClassTests.scala
  dataset/src/test/scala/frameless/LitTests.scala
  dataset/src/test/scala/frameless/RecordEncoderTests.scala
Labels: enhancement
