Repository typelevel/frameless, pull requests merged in 2021-11, with the labels that each got.

#580 Fix Spark cross publish
  .github/workflows/ci.yml
  build.sbt
Labels: fix

#488 Allow Frameless to explode Map[A,B]
  dataset/src/main/scala/frameless/TypedDataset.scala
  dataset/src/test/scala/frameless/ExplodeTests.scala
Labels: feature

#582 Resolve a possible explodeMap column names collision
  dataset/src/main/scala/frameless/TypedDataset.scala
  dataset/src/test/scala/frameless/ExplodeTests.scala
  dataset/src/test/scala/frameless/XN.scala
Labels: enhancement
