Repository typelevel/frameless, pull requests merged in 2023-06, with the labels that each got.

#699 Spark 3.4.0 and DBR 12.2 support
  .github/workflows/ci.yml
  README.md
  build.sbt
  dataset/src/main/scala/frameless/TypedEncoder.scala
  dataset/src/main/scala/frameless/functions/Lit.scala
  dataset/src/main/scala/frameless/functions/Udf.scala
  dataset/src/main/scala/frameless/ops/GroupByOps.scala
  dataset/src/main/scala/org/apache/spark/sql/FramelessInternals.scala
  dataset/src/main/scala/org/apache/spark/sql/reflection/package.scala
  dataset/src/main/spark-3.4+/frameless/MapGroups.scala
  dataset/src/main/spark-3/frameless/MapGroups.scala
  dataset/src/test/scala/frameless/ColumnTests.scala
  dataset/src/test/scala/frameless/SelfJoinTests.scala
  dataset/src/test/scala/frameless/functions/AggregateFunctionsTests.scala
  dataset/src/test/scala/frameless/package.scala
  ml/src/test/scala/frameless/ml/Generators.scala
  ml/src/test/scala/frameless/ml/clustering/KMeansTests.scala
Labels: feature

#721 Make Literals foldable, ensure Parquet predicates pushdown
  build.sbt
  dataset/src/main/scala/frameless/functions/Lit.scala
  dataset/src/main/scala/frameless/functions/package.scala
  dataset/src/test/scala/frameless/LitTests.scala
  dataset/src/test/scala/frameless/TypedDatasetSuite.scala
  dataset/src/test/scala/frameless/sql/package.scala
  dataset/src/test/scala/frameless/sql/rules/SQLRulesSuite.scala
  dataset/src/test/scala/org/apache/hadoop/fs/local/StreamingFS.scala
  dataset/src/test/spark-3.2/frameless/sql/rules/FramelessLitPushDownTests.scala
  dataset/src/test/spark-3.3+/frameless/sql/rules/FramelessLitPushDownTests.scala
Labels: enhancement

#718 Update scala-library to 2.12.18
  .github/workflows/ci.yml
  build.sbt
Labels: dependency-update
